Fix/panic
kubescape/kubescape pull request #1004
Opened 2023-01-04 14:58 UTC by darkweaver87

## Describe your changes
Fix panic while scanning files/dirs.

## Screenshots - If Any (Optional)
```
kubescape scan test.yaml
go build -v -tags="static" .
github.com/kubescape/kubescape/v2/core/pkg/policyhandler
github.com/kubescape/kubescape/v2/core/core
[info] Kubescape scanner starting
[warning] unknown build number, this might affect your scan results. Please make sure you are updated to latest version
[info] Downloading/Loading policy definitions
[success] Downloaded/Loaded policy
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x33e61fe]

goroutine 1 [running]:
github.com/kubescape/kubescape/v2/core/pkg/policyhandler.setCloudMetadata(0xc0012b4000)
	/home/rbuisson/Documents/go/src/github.com/kubescape/kubescape/core/pkg/policyhandler/handlenotification.go:91 +0x9e
github.com/kubescape/kubescape/v2/core/pkg/policyhandler.(*PolicyHandler).getResources(0xc0017a37f0, {0xc0006a0a80, 0x6, 0x8?}, 0xc0012b4000, 0x3a43bc0?)
	/home/rbuisson/Documents/go/src/github.com/kubescape/kubescape/core/pkg/policyhandler/handlenotification.go:63 +0x6d
github.com/kubescape/kubescape/v2/core/pkg/policyhandler.(*PolicyHandler).CollectResources(0xc0017a37f0, {0xc0006a0a80, 0x6, 0x8}, 0xc00028ab40)
	/home/rbuisson/Documents/go/src/github.com/kubescape/kubescape/core/pkg/policyhandler/handlenotification.go:48 +0xb9
github.com/kubescape/kubescape/v2/core/core.(*Kubescape).Scan(0x3c41a00?, 0xc00028ab40)
	/home/rbuisson/Documents/go/src/github.com/kubescape/kubescape/core/core/scan.go:158 +0x6b9
github.com/kubescape/kubescape/v2/cmd/scan.getFrameworkCmd.func2(0x36bb7e0?, {0xc0002e3b00, 0x2, 0x2})
	/home/rbuisson/Documents/go/src/github.com/kubescape/kubescape/cmd/scan/framework.go:106 +0x46c
github.com/kubescape/kubescape/v2/cmd/scan.GetScanCommand.func1(0xc00042fb00?, {0xc000383890, 0x1, 0x1?})
	/home/rbuisson/Documents/go/src/github.com/kubescape/kubescape/cmd/scan/scan.go:46 +0x166
github.com/spf13/cobra.(*Command).ValidateArgs(...)
	/home/rbuisson/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1072
github.com/spf13/cobra.(*Command).execute(0xc00042fb00?, {0xc000383790?, 0x1?, 0x1?})
	/home/rbuisson/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:885 +0x653
github.com/spf13/cobra.(*Command).ExecuteC(0xc00042f200)
	/home/rbuisson/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/home/rbuisson/.gvm/pkgsets/go1.19/global/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/kubescape/kubescape/v2/cmd.Execute()
	/home/rbuisson/Documents/go/src/github.com/kubescape/kubescape/cmd/root.go:87 +0x2d
main.main()
	/home/rbuisson/Documents/go/src/github.com/kubescape/kubescape/main.go:9 +0x1d
```

## This PR fixes:

* Resolved #

## Checklist before requesting a review

- [x] My code follows the style guidelines of this project
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [x] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

2023-01-04 15:35 UTC, matthyx commented
Hi @darkweaver87 thanks for your contribution!
Can you provide your yaml (or even better, something simplier) as a reproducer to improve our test coverage?

2023-01-05 06:26 UTC, dwertent commented
@darkweaver87 I did not manage to reproduce this issue but I'm suspecting that this issue occurs in case there is no `~/kube/config` file.
Am I correct? What is your setup?

2023-01-05 08:43 UTC, darkweaver87 commented
Hello guys,

I managed to reproduce it and find the root issue. It occurs when you have a kubeconfig set and the name of the cluster matches `.*eks.*`.

Here is the example of a k3d newly created cluster with name changed:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUyTnpFd09UVTNNakl3SGhjTk1qSXhNakUxTURreE5USXlXaGNOTXpJeE1qRXlNRGt4TlRJeQpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUyTnpFd09UVTNNakl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUdVhWQVo1OWdhN01WaExYaldNT0F0di9BY3I0RE1FQmZQNHpnREhqeSsKRStQY2JwcDZIRE9EVU5ONUEzVTE5bE41Z0d1d3AybFBvSlZQQ1lEMnNHYzBvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVW9MRzh1UW9kWE1kb05QSDZHYzhnCkdTVjdrZ293Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnQ1ovVi9qcTdJd2lLQ2JkeXZGZGxvSDJERHhPZTNzNDEKQWxZZEEvRFAwMTBDSVFEdXg1bG0rbzlJd0tzMUVtYTBpMGlMUDdieWJFcDVmVGRNRU45eldUMHJYdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://0.0.0.0:45627
  name: ekscluster
contexts:
- context:
    cluster: ekscluster
    user: admin@k3d-k3s-default
  name: k3d-k3s-default
current-context: k3d-k3s-default
kind: Config
preferences: {}
users:
- name: admin@k3d-k3s-default
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJrVENDQVRlZ0F3SUJBZ0lJRE9JQ2RpQ21EdFl3Q2dZSUtvWkl6ajBFQXdJd0l6RWhNQjhHQTFVRUF3d1kKYXpOekxXTnNhV1Z1ZEMxallVQXhOamN4TURrMU56SXlNQjRYRFRJeU1USXhOVEE1TVRVeU1sb1hEVEl6TVRJeApOVEE1TVRVeU1sb3dNREVYTUJVR0ExVUVDaE1PYzNsemRHVnRPbTFoYzNSbGNuTXhGVEFUQmdOVkJBTVRESE41CmMzUmxiVHBoWkcxcGJqQlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFKzB4dVJZRXVMZ3V3THcKOFo0NzlPcG80OEd2YzliWFhrejhuN1Yvdk1vb0l1b1QrMEdSOEp3NWI4WUdKekY0R2NVZUFtTHV1ZU93L01CSAptL2lWOGlxalNEQkdNQTRHQTFVZER3RUIvd1FFQXdJRm9EQVRCZ05WSFNVRUREQUtCZ2dyQmdFRkJRY0RBakFmCkJnTlZIU01FR0RBV2dCUVJFdjZqMlZydEZIb0hXb1RwcTFTa3ZBTVB3REFLQmdncWhrak9QUVFEQWdOSUFEQkYKQWlCYlJGNElUUm5UdnJmVjk5alNWMzFOcy8wbXdqUmtFbFA1N1RIWW5CY3pMd0loQUtQR1Y5aGhFK0IvM0lSaApkTW8wYTg0MjEwYnBMSGFVbUJUR21tc2F3UUxBCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJlRENDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdFkyeHAKWlc1MExXTmhRREUyTnpFd09UVTNNakl3SGhjTk1qSXhNakUxTURreE5USXlXaGNOTXpJeE1qRXlNRGt4TlRJeQpXakFqTVNFd0h3WURWUVFEREJock0zTXRZMnhwWlc1MExXTmhRREUyTnpFd09UVTNNakl3V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFSZWJmYlQ3M2lPMFlPTVFZMGhjcGF0QlFqaE1qM0huakJqOTJFeU45bXQKMEFnSjlQRW5BT1A5ODQ4UVdyMDNPZXVVY0JuRnI1a29XUWR0R1g5WkxuV1ZvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUVSTCtvOWxhN1JSNkIxcUU2YXRVCnBMd0REOEF3Q2dZSUtvWkl6ajBFQXdJRFNRQXdSZ0loQUw2OGRsWlhiczFBcFltQWxSTUN5RlAxQkpIeloyOEMKZ2FGOXBXeVhwaHBpQWlFQS8vbzhrcGtFb08wZ0dTT1AwOHhhVDRYWmtQdjdHY3RHb2ZqRjNjSE91UDQ9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    client-key-data: LS0tLS1CRUdJTiBFQyBQUklWQVRFIEtFWS0tLS0tCk1IY0NBUUVFSUkyNmM3UC9MMnVuTEpuOHdxQTB5WTZ3R294UlpTZG84T2lsaXR6MTRHb0JvQW9HQ0NxR1NNNDkKQXdFSG9VUURRZ0FFVDdURzVGZ1M0dUM3QXZEeG5qdjA2bWpqd2E5ejF0ZGVUUHlmdFgrOHlpZ2k2aFA3UVpIdwpuRGx2eGdZbk1YZ1p4UjRDWXU2NTQ3RDh3RWViK0pYeUtnPT0KLS0tLS1FTkQgRUMgUFJJVkFURSBLRVktLS0tLQo=
```

2023-01-05 08:48 UTC, dwertent commented
@darkweaver87 I also have a kubeconfig set with `eks` and this does not reproduce 😣. 
What Kubescape version are you running and what does the `test.yaml` file look like?

2023-01-05 08:57 UTC, darkweaver87 commented
I'm running the version `v2.0.181` and my `test.yaml` looks like:
`̀``
apiVersion: v1
kind: Namespace
metadata:
  name: test
`̀``

2023-01-05 15:18 UTC, dwertent requested changes
@darkweaver87  Thank you for taking the time and opening this PR.
I took a closer look at the issue, and I have a different solution for it ->
We can wrap calling the [setCloudMetadata](https://github.com/kubescape/kubescape/blob/b4bdf4d860d10e05406f47e90e998005fb0bfae9/core/pkg/policyhandler/handlenotification.go#L63) as follows:

```
// set cloud metadata only when scanning a cluster
if opaSessionObj.Metadata.ScanMetadata.ScanningTarget == reportv2.Cluster {
	setCloudMetadata(opaSessionObj)
}
```

I think this is a nicer solution.

Thoughts?

2023-01-06 08:48 UTC, darkweaver87 commented
Fine by me :+1:  Do you want me to update this PR or do you want to push your commit instead ?

2023-01-06 14:10 UTC, dwertent commented
@darkweaver87 Go ahead and update the PR so you can get the credit for it 😃

2023-01-06 14:33 UTC, darkweaver87 commented
I'm not searching for credits but ok, I'll do 😂

2023-01-10 06:17 UTC, dwertent approved these changes

2023-01-11 10:06 UTC, merged