Scope support
kubescape/kubescape pull request #1293
Opened 2023-07-23 19:56 UTC by rcohencyberarmor

this PR is only for checking the system test, changes are needed here! not for review yet!

2023-07-25 19:33 UTC, rcohencyberarmor commented
this PR is ready for review!

2023-07-30 08:34 UTC, Daniel-GrunbergerCA requested changes

2023-07-30 08:34 UTC, Daniel-GrunbergerCA commented on core/cautils/datastructuresmethods.go
> +func isControlFitToScanning(control reporthandling.Control, scanScope reporthandling.ScanningScopeType) bool {
why not call `isControlFitToScanScope` straight ?

2023-07-30 08:34 UTC, Daniel-GrunbergerCA commented on core/cautils/datastructuresmethods.go
> +func (policies *Policies) Set(frameworks []reporthandling.Framework, version string, scanInfo *ScanInfo) {
do we need to pass `*ScanInfo` or just `scanningContext`?

2023-07-30 08:34 UTC, Daniel-GrunbergerCA commented on core/cautils/sliceutils.go
> +func IsSubSliceScanningScopeType(haystack []reporthandling.ScanningScopeType, needle []reporthandling.ScanningScopeType) bool {
I am pretty sure there are more easily readable algorithms that can achieve that

2023-07-30 08:34 UTC, Daniel-GrunbergerCA commented on core/cautils/datastructuresmethods.go
> +		isCloud, cloudType := getCloudType(scanInfo)
pls mind the linter comments

2023-07-30 12:32 UTC, Daniel-GrunbergerCA commented on core/cautils/datastructuresmethods_test.go
> +func TestIsControlFitToScanning(t *testing.T) {
```suggestion
func TestIsControlFitToScanScope(t *testing.T) {
```

2023-07-30 12:35 UTC, Daniel-GrunbergerCA approved these changes

2023-07-31 06:40 UTC, Daniel-GrunbergerCA approved these changes

2023-08-03 04:55 UTC, dwertent commented
/describe

2023-08-07 16:11 UTC, dwertent approved these changes

2023-08-07 16:11 UTC, merged