Improve cluster scan cli
kubescape/kubescape pull request #1352
Opened 2023-08-20 10:58 UTC by Daniel-GrunbergerCA

## Overview
This PR mainly improves the CLI output for a cluster scan by changing the texts for it and adding more explanation texts.
 It also fixes the submission behavior for when the security view is activated

2023-08-21 18:44 UTC, Daniel-GrunbergerCA commented on core/core/initutils.go
> +	if !scanInfo.FrameworkScan && scanInfo.ScanType != cautils.ScanTypeCluster && scanInfo.ScanType != cautils.ScanTypeRepo {
I haved added an type for control, and changed the code. Pls take a look

2023-08-21 19:00 UTC, Daniel-GrunbergerCA commented on core/pkg/resultshandling/printer/v2/prettyprinter.go
> +		if pp.scanType != cautils.ScanTypeCluster && pp.scanType != cautils.ScanTypeRepo && pp.scanType != cautils.ScanTypeWorkload {
moved to function

2023-08-22 05:08 UTC, dwertent requested changes

2023-08-22 05:08 UTC, dwertent commented on core/core/initutils.go
> +	if scanInfo.ScanType == cautils.ScanTypeControl || scanInfo.ScanType == cautils.ScanTypeWorkload {
We should have a unit test covering this behavior

2023-08-22 12:20 UTC, dwertent approved these changes

2023-08-22 12:21 UTC, merged