support delete paths and review paths
kubescape/kubescape pull request #1402
Opened 2023-10-01 09:43 UTC by YiscahLevySilas1

## Overview

2023-10-01 09:50 UTC, dwertent requested changes

2023-10-01 09:50 UTC, dwertent commented on go.mod
> +	github.com/armosec/armoapi-go v0.0.256-0.20230928144732-6dc515782a26
```suggestion
	github.com/armosec/armoapi-go v0.0.256
```

2023-10-01 13:13 UTC, dwertent commented
Can you please add a screenshot of what the "new paths" look like?
e.g.
```
$ kubescape scan control c-0034 workload.yaml -v
┌──────────┬────────────────────────────────┬────────────────────────────────────┬────────────────────────────────────┐
│ SEVERITY │          CONTROL NAME          │                DOCS                │        ASSISTED REMEDIATION        │
├──────────┼────────────────────────────────┼────────────────────────────────────┼────────────────────────────────────┤
│ Medium   │ Automatic mapping of service   │ https://hub.armosec.io/docs/c-0034 │ automountServiceAccountToken=false │
│          │ account                        │                                    │                                    │
└──────────┴────────────────────────────────┴────────────────────────────────────┴────────────────────────────────────┘
```

2023-10-01 19:42 UTC, YiscahLevySilas1 commented
> Can you please add a screenshot of what the "new paths" look like? e.g.
> 
> ```
> $ kubescape scan control c-0034 workload.yaml -v
> ┌──────────┬────────────────────────────────┬────────────────────────────────────┬────────────────────────────────────┐
> │ SEVERITY │          CONTROL NAME          │                DOCS                │        ASSISTED REMEDIATION        │
> ├──────────┼────────────────────────────────┼────────────────────────────────────┼────────────────────────────────────┤
> │ Medium   │ Automatic mapping of service   │ https://hub.armosec.io/docs/c-0034 │ automountServiceAccountToken=false │
> │          │ account                        │                                    │                                    │
> └──────────┴────────────────────────────────┴────────────────────────────────────┴────────────────────────────────────┘
> ```

Thanks for your comment, I added back support for failedPaths until we add the new paths to all relevant controls.
As for your question - It will look the same.

current ks scan:
![image](https://github.com/kubescape/kubescape/assets/80635572/afa4eed8-6d92-41df-a57e-e7dedf80b49b)

After PR changes, before adding new paths to rules:
![image](https://github.com/kubescape/kubescape/assets/80635572/9dc80bb7-7942-4ad8-8eee-088a1c8cd574)

After PR changes, using a rule that supports both failedPaths and reviewPath:
![image](https://github.com/kubescape/kubescape/assets/80635572/e3d1ba5c-02be-4c1a-be8f-85ac0ac847d6)

2023-10-02 14:02 UTC, dwertent approved these changes

2023-10-02 14:03 UTC, merged