Tests/core/core/initutils and potential bug avoided
kubescape/kubescape pull request #1501
Opened 2023-11-23 14:39 UTC by mohaidoss

## Overview

2023-11-23 14:40 UTC, mohaidoss commented
/describe

2023-11-23 14:59 UTC, mohaidoss commented
Some tests are missing for functions that call `SetRegoObjects`, because I couldn't mock that function (AI seems clueless too)...  

If someone knowledgeable can help out, It would really help here! I'm new to the language :cry:

2023-11-23 15:30 UTC, mohaidoss commented
@matthyx One of the tests are failing `TestGenerateTableWithCorrectHeadersAndRows`
Not expecting colors on the output..

2023-11-23 16:14 UTC, matthyx commented
@mohaidoss can you rebase?

2023-11-23 16:37 UTC, mohaidoss commented
@matthyx Yes, it is good now. I reverted my very recent changes

2023-11-24 08:35 UTC, matthyx requested changes

2023-11-24 10:36 UTC, mohaidoss commented on core/core/initutils_test.go
> +func TestGetDownloadReleasedPolicyError(t *testing.T) {
Removed

2023-11-24 11:13 UTC, matthyx approved these changes

2023-11-24 11:13 UTC, merged