added support for exception rules
kubescape/kubescape pull request #1591
Opened 2024-01-21 17:09 UTC by Sanskarzz

## Overview

- Update opa-utils from v0.0.273 to v0.0.275 to add Exception in --data payload
- Added loadexception function which runs when scanRequest or payload contains an Exception  

## Examples/Screenshots
Here is the command to test weather the Exception Payload is load or not 
```
curl --header "Content-Type: application/json"   --request POST   --data '{"Exceptions": [{"name":"exclude-allowed-hostPath-control","policyType":"postureExceptionPolicy","actions":["alertOnly"],"resources":[{"designatorType":"Attributes","attributes":{"kind":".*"}}],"posturePolicies":[{"controlName":"HostPath mount"}]}]}'   http://127.0.0.1:8080/v1/scan

```
I used this Exception example [exclude-allowed-hostPath-control](https://github.com/kubescape/kubescape/blob/master/examples/exceptions/exclude-allowed-hostPath-control.json)
> Here are results screenshots
![Screenshot from 2024-01-21 22-36-52](https://github.com/kubescape/kubescape/assets/92817635/5b3a89f9-1915-4194-8e2e-d09311575554)

## Related issues/PRs:
fixes : #1580 
@xdavidel

2024-02-05 09:52 UTC, dwertent requested changes

2024-02-05 10:12 UTC, Sanskarzz commented on httphandler/handlerequests/v1/datastructuremethods.go
> +func loadexception(exceptions *utilsmetav1.PostScanRequest) (path string) {
scanInfo.UseExceptions accepts 1 variable

2024-02-05 12:03 UTC, dwertent commented
https://github.com/kubescape/kubescape/pull/1591#issuecomment-1926640552
You will need to handle the error from the returned function.
If there is an error, print a warning message.

2024-02-05 13:05 UTC, dwertent requested changes

2024-02-05 13:05 UTC, dwertent commented on httphandler/handlerequests/v1/datastructuremethods.go
> +		fmt.Printf("Failed to get executable path, reason: %s", err)
Return error

2024-02-05 13:05 UTC, dwertent commented on httphandler/handlerequests/v1/datastructuremethods.go
> +		scanInfo.UseExceptions, _ = loadException(scanRequest)
Manage returned error

2024-02-06 06:02 UTC, dwertent requested changes

2024-02-06 06:02 UTC, dwertent commented on httphandler/handlerequests/v1/datastructuremethods.go
> +			fmt.Println("failed to load exceptions:", err)
Use the Kubescape logger instead of `fmt.Println`

2024-02-12 16:13 UTC, Sanskarzz commented
any update on this

2024-03-04 13:03 UTC, dwertent commented
@Sanskarzz Please rebase from main :)

2024-08-05 20:31 UTC, matthyx approved these changes

2025-02-07 12:32 UTC, merged