improved icon of kubescape in readme
kubescape/kubescape pull request #690
Opened 2022-08-25 09:34 UTC by legendarykamal

## Describe your changes

Fixes #689

1> The icon was centre aligned giving it a better look and feel.
2> we have asked users to give a star to the repo .

## Screenshots - If Any (Optional)
Latest Improvement 

![image](https://user-images.githubusercontent.com/95926324/186751852-9425d9b3-55b6-478b-a18a-1d2b2467a8e5.png)

## Issue ticket number and link

## Checklist before requesting a review
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

2022-08-25 17:57 UTC, vladklokun requested changes
Good catches! Let’s refine the PR a bit and move to merging it.

Please also note that according to our [contribution guidelines](https://github.com/kubescape/kubescape/blob/f3623dccf65df2ba2006c4b2917aa94d528bcf59/CONTRIBUTING.md) Pull Requests should target the `dev` branch, not the `master`. So please rebase your commits on `dev` before submitting your changes again.

Thanks!

2022-08-25 17:57 UTC, vladklokun commented on README.md
> +</div>
issue: logo is centered, but the badges aren’t

The badges look lonely that way. Let’s add a horizontal rule to visually separate the logo and anchor the badges to the rule.

```suggestion
<div align="center">
    <img src="docs/kubescape.png" width="300" alt="logo">
</div>

---

```

2022-08-25 17:57 UTC, vladklokun commented on README.md
> +### and if you want us to continue to develop and improve Kubescape 😀 .
issue: the heading splits in two, sentence should be grammatically improved

Let’s change it so the header stays put and make the sentence a bit more idiomatic.

```suggestion
### [Star ⭐](https://github.com/kubescape/kubescape/stargazers) the repo if you want us to continue developing and improving Kubescape 😀
```

2022-08-25 19:20 UTC, legendarykamal commented
Nice suggestions @vladklokun :smile: I will refine it

2022-08-25 19:56 UTC, vladklokun commented
> But it did mention that unless they are documentary changes since this was one so i made it against master.

Oh, did it? I can’t find it. Could you point me to where you’ve seen that, please?

2022-08-25 20:00 UTC, vladklokun approved these changes

2022-08-25 20:06 UTC, vladklokun commented
Good job, looks good to me :)

We will be merging this shortly.

2022-08-26 03:32 UTC, legendarykamal commented
Thanks @vladklokun :fireworks: 



> > But it did mention that unless they are documentary changes since this was one so i made it against master.
> 
> Oh, did it? I can’t find it. Could you point me to where you’ve seen that, please?

Yes, sure look in this 
![image](https://user-images.githubusercontent.com/95926324/186811810-68f32695-2cca-44eb-835c-9c8b3378cf7b.png)

2022-08-26 10:01 UTC, vladklokun commented
Oh, it was the PR template, not the contribution guildelines. You’re right. We will have to adjust them accordingly :)

2022-08-26 11:47 UTC, merged