Update roadmap.md
kubescape/kubescape pull request #824
Opened 2022-09-16 04:27 UTC by Yh010

2022-09-25 04:54 UTC, anubhav06 requested changes

2022-09-25 04:54 UTC, anubhav06 commented on docs/roadmap.md
> +Kubescape roadmap items are labeled based on where the feature is used and by it's maturity.
`their` was correct. No need for this.

2022-09-25 04:54 UTC, anubhav06 commented on docs/roadmap.md
> +  We want to expand Kubescape to integrate with different image registries and read image vulnerability information from there. This will allow Kubescape to give contextual security information about
Remove the whitespace before `We`

2022-11-02 06:23 UTC, dwertent commented
It looks like you used a tool for rendering the changes without confirming the changes are actually needed or correct

2022-11-02 06:23 UTC, closed without merging