add Container resources to resources list
kubescape/kubescape pull request #874
Opened 2022-10-23 11:44 UTC by cigra

## Describe your changes

## This PR fixes:
add Container resources to resources list

## Checklist before requesting a review

- [ ] My code follows the style guidelines of this project
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

2022-10-23 12:46 UTC, Bezbran requested changes

2022-10-23 12:46 UTC, Bezbran commented on core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
> +			ResourceID:  uuid.NewString(),
FNV of ParentResourceID + containerName

2022-10-23 15:59 UTC, avrahams commented on core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
> +	ParentKind      string `json:"parentKind"`
should we also add parent api version ?

2022-10-23 16:02 UTC, avrahams commented on core/pkg/resultshandling/reporter/v2/container_test.go
> +			resorce: `{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"creationTimestamp":"2021-05-03T13:10:32Z","generation":1,"managedFields":
nicer to use embed and a json file

2022-10-23 17:42 UTC, dwertent requested changes

2022-10-23 17:42 UTC, dwertent commented on core/pkg/resultshandling/reporter/v2/container.go
> +	ParentKind       string `json:"parentKind"`
Hi, I think we should have an object representing the parent (similar to the `ownerReferences` object)

2022-10-24 08:54 UTC, avrahams commented on core/pkg/resultshandling/reporter/v2/container.go
> +}
Metadata      metav1.ObjectMeta `json:"metadata"`
metav1.TypeMeta `json:",inline"`

2022-10-25 08:06 UTC, dwertent requested changes
@Bezbran I don't understand why this data is generated in kubescape and sent to the BE.
This should be aggregated before inserting the pods to Elastic, simply extract the container out of the pod (exactly what KS is doing...).
Is there a reason this is happening in Kubescape?

2022-10-25 08:06 UTC, dwertent commented on core/pkg/resultshandling/reporter/v2/reporteventreceiver.go
> +		containers := rawResourceContainerHandler(*resource)
Call this function BEFORE sending resources to the BE (we first collect all the resources we want to send and only then we start sending).
This should happen around [here](https://github.com/kubescape/kubescape/blob/master/core/pkg/resourcehandler/k8sresources.go#L69).

2022-10-27 05:54 UTC, closed without merging