Add support to exceptions on repo (files) scan
kubescape/kubescape pull request #892
Opened 2022-11-02 10:54 UTC by Moshe-Rappaport-CA

## Describe your changes
I added the `path` key to the exceptions object in armoapi-go and opa-utils
## Checklist before requesting a review

- [ ] My code follows the style guidelines of this project
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added thorough tests.
- [ ] New and existing unit tests pass locally with my changes

**Please open the PR against the `dev` branch (Unless the PR contains only documentation changes)**

2022-11-02 10:55 UTC, dwertent approved these changes

2022-11-03 07:11 UTC, dwertent requested changes
Please share a screenshot of the new message.

2022-11-03 07:11 UTC, dwertent commented on core/pkg/resultshandling/reporter/v2/mockreporter.go
> +	// message += "Sign up for free: "
Remove the commented out code

2022-11-03 07:57 UTC, Moshe-Rappaport-CA commented
![image](https://user-images.githubusercontent.com/89577611/199671067-5531f151-85cf-450c-8d91-7140bb56fbe7.png)

2022-11-03 08:07 UTC, dwertent approved these changes

2022-11-03 08:07 UTC, merged