added override values for helm feature
kubescape/kubescape pull request #932
Opened 2022-11-21 10:30 UTC by AvineshTripathi

fixes #901

With merge of this PR kubescape will support a flag `--helm-value-file` which takes input of path/paths of value file seperated by `,` and override the default value file of helm.

Approach:

The working of this feature is similiar to what `helm/helm` repo handles overriding however due to different structures I could not use those functions. ref https://github.com/helm/helm/blob/main/pkg/cli/values/options.go#L42

2022-11-22 10:56 UTC, AvineshTripathi commented
Update: fixing test cases

2022-11-24 08:04 UTC, dwertent commented
@AvineshTripathi the checks failed

2022-11-27 14:22 UTC, dwertent requested changes
I'm missing the mapping between the chart and the values file.
e.g. A directory with multiple helm charts and you want to override one of the values file, how will you do it?

2022-11-27 14:22 UTC, dwertent commented on core/cautils/helmchart.go
> +func mergeMaps(a, b map[string]interface{}) map[string]interface{} {
Please add some unitests for this function

2022-11-27 19:52 UTC, AvineshTripathi commented
> I'm missing the mapping between the chart and the values file. e.g. A directory with multiple helm charts and you want to override one of the values file, how will you do it?

can you explain the example in more detail please?

2022-12-09 12:51 UTC, AvineshTripathi commented
@dwertent ^^

2023-01-16 10:10 UTC, dwertent commented
@AvineshTripathi I'm waiting for the check to pass before I review :)

2023-01-16 10:19 UTC, AvineshTripathi commented
Hey @dwertent thanks for the response however I am facing a lot trouble with conflicts(shared in slack as well).
To explain more,

I did changes and pushed to PR but it showed conflicts in a file which was not changed by my PR later as I resolved the conflicts build started throwing error in the same file of resolved conflicts. This situation has been constant for me even after resolving conflicts in previous PR as well so I need some help with it

2023-02-01 13:54 UTC, AvineshTripathi commented
Hey folks I tried again resolving the conflicts still things remain same so I would need some help in resolving the conflicts. The branch is working perfectly when run locally

2023-03-24 10:30 UTC, matthyx commented
@AvineshTripathi do you still need help with conflicts?

2023-10-09 08:27 UTC, matthyx commented
@AvineshTripathi do we want to revisit this?

2023-10-15 08:59 UTC, dwertent commented
Stale PR

2023-10-15 08:59 UTC, closed without merging